[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "build"
[build.environment]
  VUE_APP_INFURA_ID = "6dccc3daffad46d280f872d4a73721e1"
  FAUNADB_SERVER_SECRET = "fnAESiNtj_ACQAVh6pM8vECd16tCQka6SQqH6Fwu"
  ALCHEMY_SECRET = "ihOBDG_dRc85G3mbQvLDpbWm-fXn8UCq"
  NFT_CONTRACT_ADDRESS = '0x1dfe7Ca09e99d10835Bf73044a23B73Fc20623DF'